//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BDUnderMatchEntities1 : DbContext
    {
        public BDUnderMatchEntities1()
            : base("name=BDUnderMatchEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ctgCategorias> ctgCategorias { get; set; }
        public virtual DbSet<ctgTipoArbitros> ctgTipoArbitros { get; set; }
        public virtual DbSet<ctgTipoEmpleados> ctgTipoEmpleados { get; set; }
        public virtual DbSet<ctgTipoProveedores> ctgTipoProveedores { get; set; }
        public virtual DbSet<Jugadores_Equipos> Jugadores_Equipos { get; set; }
        public virtual DbSet<tblArbitros> tblArbitros { get; set; }
        public virtual DbSet<tblCanchas> tblCanchas { get; set; }
        public virtual DbSet<tblEmpleados> tblEmpleados { get; set; }
        public virtual DbSet<tblEquipos> tblEquipos { get; set; }
        public virtual DbSet<tblJugadores> tblJugadores { get; set; }
        public virtual DbSet<tblPartidos> tblPartidos { get; set; }
        public virtual DbSet<tblPersonas> tblPersonas { get; set; }
        public virtual DbSet<tblPlanteles> tblPlanteles { get; set; }
        public virtual DbSet<tblProveedores> tblProveedores { get; set; }
        public virtual DbSet<tblTemporadas> tblTemporadas { get; set; }
        public virtual DbSet<viewJugadores> viewJugadores { get; set; }
        public virtual DbSet<viewArbitros> viewArbitros { get; set; }
    
        public virtual int tblJugadoresAgregar(string nombre, string primerApellido, string segundoApellido, string fechaNacimiento, string sexo, string telefono, string telefono2, string correo, string numDorsal, string sobreNombre, string posicion, Nullable<int> capitan, Nullable<int> idEquipo)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var numDorsalParameter = numDorsal != null ?
                new ObjectParameter("NumDorsal", numDorsal) :
                new ObjectParameter("NumDorsal", typeof(string));
    
            var sobreNombreParameter = sobreNombre != null ?
                new ObjectParameter("SobreNombre", sobreNombre) :
                new ObjectParameter("SobreNombre", typeof(string));
    
            var posicionParameter = posicion != null ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(string));
    
            var capitanParameter = capitan.HasValue ?
                new ObjectParameter("Capitan", capitan) :
                new ObjectParameter("Capitan", typeof(int));
    
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblJugadoresAgregar", nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, sexoParameter, telefonoParameter, telefono2Parameter, correoParameter, numDorsalParameter, sobreNombreParameter, posicionParameter, capitanParameter, idEquipoParameter);
        }
    
        public virtual int tblJugadoresEliminar(Nullable<int> idJugador, Nullable<int> eliminar)
        {
            var idJugadorParameter = idJugador.HasValue ?
                new ObjectParameter("IdJugador", idJugador) :
                new ObjectParameter("IdJugador", typeof(int));
    
            var eliminarParameter = eliminar.HasValue ?
                new ObjectParameter("Eliminar", eliminar) :
                new ObjectParameter("Eliminar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblJugadoresEliminar", idJugadorParameter, eliminarParameter);
        }
    
        public virtual int tblJugadoresModificar(Nullable<int> idPersona, string nombre, string primerApellido, string segundoApellido, string fechaNacimiento, string sexo, string telefono, string telefono2, string correo, Nullable<int> idJugador, string numDorsal, string sobreNombre, string posicion, Nullable<int> capitan, Nullable<int> idEquipo)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var idJugadorParameter = idJugador.HasValue ?
                new ObjectParameter("IdJugador", idJugador) :
                new ObjectParameter("IdJugador", typeof(int));
    
            var numDorsalParameter = numDorsal != null ?
                new ObjectParameter("NumDorsal", numDorsal) :
                new ObjectParameter("NumDorsal", typeof(string));
    
            var sobreNombreParameter = sobreNombre != null ?
                new ObjectParameter("SobreNombre", sobreNombre) :
                new ObjectParameter("SobreNombre", typeof(string));
    
            var posicionParameter = posicion != null ?
                new ObjectParameter("Posicion", posicion) :
                new ObjectParameter("Posicion", typeof(string));
    
            var capitanParameter = capitan.HasValue ?
                new ObjectParameter("Capitan", capitan) :
                new ObjectParameter("Capitan", typeof(int));
    
            var idEquipoParameter = idEquipo.HasValue ?
                new ObjectParameter("IdEquipo", idEquipo) :
                new ObjectParameter("IdEquipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblJugadoresModificar", idPersonaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, sexoParameter, telefonoParameter, telefono2Parameter, correoParameter, idJugadorParameter, numDorsalParameter, sobreNombreParameter, posicionParameter, capitanParameter, idEquipoParameter);
        }
    
        public virtual int tblEquiposActivar(Nullable<int> iD_EQUIPO)
        {
            var iD_EQUIPOParameter = iD_EQUIPO.HasValue ?
                new ObjectParameter("ID_EQUIPO", iD_EQUIPO) :
                new ObjectParameter("ID_EQUIPO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblEquiposActivar", iD_EQUIPOParameter);
        }
    
        public virtual int tblEquiposEliminar(Nullable<int> iD_EQUIPO)
        {
            var iD_EQUIPOParameter = iD_EQUIPO.HasValue ?
                new ObjectParameter("ID_EQUIPO", iD_EQUIPO) :
                new ObjectParameter("ID_EQUIPO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblEquiposEliminar", iD_EQUIPOParameter);
        }
    
        public virtual int tblArbitrosAgregar(string nombre, string primerApellido, string segundoApellido, string fechaNacimiento, string sexo, string telefono, string telefono2, string correo, Nullable<decimal> costoArbitraje, Nullable<int> categoria, Nullable<int> tipoArbitro)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var costoArbitrajeParameter = costoArbitraje.HasValue ?
                new ObjectParameter("CostoArbitraje", costoArbitraje) :
                new ObjectParameter("CostoArbitraje", typeof(decimal));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(int));
    
            var tipoArbitroParameter = tipoArbitro.HasValue ?
                new ObjectParameter("TipoArbitro", tipoArbitro) :
                new ObjectParameter("TipoArbitro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblArbitrosAgregar", nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, sexoParameter, telefonoParameter, telefono2Parameter, correoParameter, costoArbitrajeParameter, categoriaParameter, tipoArbitroParameter);
        }
    
        public virtual int tblArbitrosActivar(Nullable<int> idArbitro)
        {
            var idArbitroParameter = idArbitro.HasValue ?
                new ObjectParameter("IdArbitro", idArbitro) :
                new ObjectParameter("IdArbitro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblArbitrosActivar", idArbitroParameter);
        }
    
        public virtual int tblArbitrosEliminar(Nullable<int> idArbitro, Nullable<int> eliminar)
        {
            var idArbitroParameter = idArbitro.HasValue ?
                new ObjectParameter("IdArbitro", idArbitro) :
                new ObjectParameter("IdArbitro", typeof(int));
    
            var eliminarParameter = eliminar.HasValue ?
                new ObjectParameter("Eliminar", eliminar) :
                new ObjectParameter("Eliminar", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblArbitrosEliminar", idArbitroParameter, eliminarParameter);
        }
    
        public virtual int tblArbitrosModificar(Nullable<int> idPersona, string nombre, string primerApellido, string segundoApellido, string fechaNacimiento, string sexo, string telefono, string telefono2, string correo, Nullable<int> idArbitro, Nullable<decimal> costoArbitraje, Nullable<int> categoria, Nullable<int> tipoArbitro)
        {
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("IdPersona", idPersona) :
                new ObjectParameter("IdPersona", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var primerApellidoParameter = primerApellido != null ?
                new ObjectParameter("PrimerApellido", primerApellido) :
                new ObjectParameter("PrimerApellido", typeof(string));
    
            var segundoApellidoParameter = segundoApellido != null ?
                new ObjectParameter("SegundoApellido", segundoApellido) :
                new ObjectParameter("SegundoApellido", typeof(string));
    
            var fechaNacimientoParameter = fechaNacimiento != null ?
                new ObjectParameter("FechaNacimiento", fechaNacimiento) :
                new ObjectParameter("FechaNacimiento", typeof(string));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("Telefono", telefono) :
                new ObjectParameter("Telefono", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var idArbitroParameter = idArbitro.HasValue ?
                new ObjectParameter("IdArbitro", idArbitro) :
                new ObjectParameter("IdArbitro", typeof(int));
    
            var costoArbitrajeParameter = costoArbitraje.HasValue ?
                new ObjectParameter("CostoArbitraje", costoArbitraje) :
                new ObjectParameter("CostoArbitraje", typeof(decimal));
    
            var categoriaParameter = categoria.HasValue ?
                new ObjectParameter("Categoria", categoria) :
                new ObjectParameter("Categoria", typeof(int));
    
            var tipoArbitroParameter = tipoArbitro.HasValue ?
                new ObjectParameter("TipoArbitro", tipoArbitro) :
                new ObjectParameter("TipoArbitro", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("tblArbitrosModificar", idPersonaParameter, nombreParameter, primerApellidoParameter, segundoApellidoParameter, fechaNacimientoParameter, sexoParameter, telefonoParameter, telefono2Parameter, correoParameter, idArbitroParameter, costoArbitrajeParameter, categoriaParameter, tipoArbitroParameter);
        }
    }
}
