//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados_Planteles
    {
        public int IdRelacionEmpleadoPlantel { get; set; }
        public int IdEmpleado { get; set; }
        public int IdPlantel { get; set; }

        [JsonIgnore]
        public virtual tblPlanteles tblPlanteles { get; set; }
        [JsonIgnore]
        public virtual tblEmpleados tblEmpleados { get; set; }
    }
}
