//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleados
    {
        public int IdEmpleado { get; set; }
        public int IdPersona { get; set; }
        public int IdPlantel { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Curp { get; set; }
        public int TipoEmpleado { get; set; }
        public string Rfc { get; set; }
        public string Nss { get; set; }
        public decimal Salario { get; set; }
        public string Horario { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual ctgTipoEmpleados ctgTipoEmpleados { get; set; }
        public virtual tblPersonas tblPersonas { get; set; }
        public virtual tblPlanteles tblPlanteles { get; set; }
    }
}
