//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmpleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmpleados()
        {
            this.Empleados_Planteles = new HashSet<Empleados_Planteles>();
        }
    
        public int IdEmpleado { get; set; }
        public int IdPersona { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Colonia { get; set; }
        public string CodigoPostal { get; set; }
        public string Ciudad { get; set; }
        public string Estado { get; set; }
        public string Curp { get; set; }
        public int TipoEmpleado { get; set; }
        public string Rfc { get; set; }
        public string Nss { get; set; }
        public decimal Salario { get; set; }
        public string Horario { get; set; }
        public Nullable<int> Estatus { get; set; }
    
        public virtual ctgTipoEmpleados ctgTipoEmpleados { get; set; }
        public virtual tblPersonas tblPersonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados_Planteles> Empleados_Planteles { get; set; }
    }
}
