//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPartidos
    {
        public int IdPartido { get; set; }
        public int IdCancha { get; set; }
        public Nullable<int> IdTemporada { get; set; }
        public Nullable<int> Jornada { get; set; }
        public string Dia { get; set; }
        public string Hora { get; set; }
        public int Equipo1 { get; set; }
        public int Equipo2 { get; set; }
        public Nullable<int> GolesEquipo1 { get; set; }
        public Nullable<int> GolesEquipo2 { get; set; }
        public Nullable<int> Ganador { get; set; }
        public Nullable<int> Perdedor { get; set; }
        public Nullable<int> IdArbitro { get; set; }
    
        public virtual tblArbitros tblArbitros { get; set; }
        public virtual tblCanchas tblCanchas { get; set; }
        public virtual tblEquipos tblEquipos { get; set; }
        public virtual tblEquipos tblEquipos1 { get; set; }
        public virtual tblTemporadas tblTemporadas { get; set; }
    }
}
