//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewCanchas
    {
        public int IdCancha { get; set; }
        public int IdPlantel { get; set; }
        public string Nombre { get; set; }
        public int IdTipoCancha { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string TipoCancha { get; set; }
        public string Plantel { get; set; }
    }
}
