//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_UnderMatch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPartidos
    {
        public int IdPartido { get; set; }
        public int IdCancha { get; set; }
        public Nullable<int> IdTemporada { get; set; }
        public Nullable<int> Jornada { get; set; }
        public string Dia { get; set; }
        public string Hora { get; set; }
        public int IdEquipo1 { get; set; }
        public int IdEquipo2 { get; set; }
        public Nullable<int> GolesEquipo1 { get; set; }
        public Nullable<int> GolesEquipo2 { get; set; }
        public Nullable<int> Ganador { get; set; }
        public Nullable<int> Perdedor { get; set; }
        public Nullable<int> IdArbitro { get; set; }
        public Nullable<int> Estatus { get; set; }
        public string NombreCancha { get; set; }
        public string NombreEquipo1 { get; set; }
        public string NombreEquipo2 { get; set; }
        public string NombreArbitro { get; set; }
        public Nullable<decimal> CostoArbitraje { get; set; }
        public string nombreTemporada { get; set; }
    }
}
